/**
 * @file xsd vocabulary
 */

import { vocab } from "./utils.ts";

export default vocab(
  "http://www.w3.org/2001/XMLSchema#",
  "anyURI",
  "base64Binary",
  "boolean",
  "byte",
  "date",
  "dayTimeDuration",
  "dateTime",
  "dateTimeStamp",
  "decimal",
  "double",
  "duration",
  "float",
  "gDay",
  "gMonth",
  "gMonthDay",
  "gYear",
  "gYearMonth",
  "hexBinary",
  "int",
  "integer",
  "language",
  "long",
  "Name",
  "NCName",
  "negativeInteger",
  "NMToken",
  "nonNegativeInteger",
  "nonPositiveInteger",
  "normalizedString",
  "positiveInteger",
  "time",
  "short",
  "string",
  "token",
  "unsignedByte",
  "unsignedInt",
  "unsignedLong",
  "unsignedShort",
  "yearMonthDuration",
);
