/**
 * @file xsd vocabulary
 */

import { NamedNode } from "../model.ts";

function owl(name: string): NamedNode {
  return {
    tag: "named",
    iri: "http://www.w3.org/2002/07/owl#" + name,
  };
}

export default {
  "allValuesFrom": owl("allValuesFrom"),
  "annotatedProperty": owl("annotatedProperty"),
  "annotatedSource": owl("annotatedSource"),
  "annotatedTarget": owl("annotatedTarget"),
  "assertionProperty": owl("assertionProperty"),
  "cardinality": owl("cardinality"),
  "complementOf": owl("complementOf"),
  "datatypeComplementOf": owl("datatypeComplementOf"),
  "differentFrom": owl("differentFrom"),
  "disjointUnionOf": owl("disjointUnionOf"),
  "disjointWith": owl("disjointWith"),
  "distinctMembers": owl("distinctMembers"),
  "equivalentClass": owl("equivalentClass"),
  "equivalentProperty": owl("equivalentProperty"),
  "hasKey": owl("hasKey"),
  "hasSelf": owl("hasSelf"),
  "hasValue": owl("hasValue"),
  "intersectionOf": owl("intersectionOf"),
  "inverseOf": owl("inverseOf"),
  "maxCardinality": owl("maxCardinality"),
  "maxQualifiedCardinality": owl("maxQualifiedCardinality"),
  "members": owl("members"),
  "minCardinality": owl("minCardinality"),
  "minQualifiedCardinality": owl("minQualifiedCardinality"),
  "onClass": owl("onClass"),
  "onDataRange": owl("onDataRange"),
  "onDatatype": owl("onDatatype"),
  "onProperties": owl("onProperties"),
  "onProperty": owl("onProperty"),
  "oneOf": owl("oneOf"),
  "propertyChainAxiom": owl("propertyChainAxiom"),
  "propertyDisjointWith": owl("propertyDisjointWith"),
  "qualifiedCardinality": owl("qualifiedCardinality"),
  "sameAs": owl("sameAs"),
  "someValuesFrom": owl("someValuesFrom"),
  "sourceIndividual": owl("sourceIndividual"),
  "targetIndividual": owl("targetIndividual"),
  "targetValue": owl("targetValue"),
  "unionOf": owl("unionOf"),
  "withRestrictions": owl("withRestrictions"),
  "AllDifferent": owl("AllDifferent"),
  "AllDisjointClasses": owl("AllDisjointClasses"),
  "AllDisjointProperties": owl("AllDisjointProperties"),
  "Annotation": owl("Annotation"),
  "AnnotationProperty": owl("AnnotationProperty"),
  "AsymmetricProperty": owl("AsymmetricProperty"),
  "Axiom": owl("Axiom"),
  "Class": owl("Class"),
  "DataRange": owl("DataRange"),
  "DatatypeProperty": owl("DatatypeProperty"),
  "DeprecatedClass": owl("DeprecatedClass"),
  "DeprecatedProperty": owl("DeprecatedProperty"),
  "FunctionalProperty": owl("FunctionalProperty"),
  "InverseFunctionalProperty": owl("InverseFunctionalProperty"),
  "IrreflexiveProperty": owl("IrreflexiveProperty"),
  "NamedIndividual": owl("NamedIndividual"),
  "NegativePropertyAssertion": owl("NegativePropertyAssertion"),
  "ObjectProperty": owl("ObjectProperty"),
  "Ontology": owl("Ontology"),
  "OntologyProperty": owl("OntologyProperty"),
  "ReflexiveProperty": owl("ReflexiveProperty"),
  "Restriction": owl("Restriction"),
  "SymmetricProperty": owl("SymmetricProperty"),
  "TransitiveProperty": owl("TransitiveProperty"),
  "backwardCompatibleWith": owl("backwardCompatibleWith"),
  "deprecated": owl("deprecated"),
  "incompatibleWith": owl("incompatibleWith"),
  "priorVersion": owl("priorVersion"),
  "versionInfo": owl("versionInfo"),
  "Nothing": owl("Nothing"),
  "Thing": owl("Thing"),
  "bottomDataProperty": owl("bottomDataProperty"),
  "topDataProperty": owl("topDataProperty"),
  "bottomObjectProperty": owl("bottomObjectProperty"),
  "topObjectProperty": owl("topObjectProperty"),
  "imports": owl("imports"),
  "versionIRI": owl("versionIRI"),
  "rational": owl("rational"),
  "real": owl("real"),
};
